#spring.application.name=demo

spring.datasource.url=jdbc:postgresql://dpg-d9ikcqb7uimc73bo70a0-a:5432/task_db_nbuv
spring.datasource.username=task_db_nbuv_user
spring.datasource.password=IaHZCtQ3eJY4stvGjCwfQblAIKGi2Wq7
spring.jpa.hibernate.ddl-auto=update
